### ISSUE TITLE
Error: Cannot find module '@storybook/preview-web/package.json' ERR! Require stack: 

### ISSUE THREAD

**Issue by productdevbook** [eirslett/storybook-builder-vite#163] opened 2021-11-20 17:34 UTC
v0.1.9

**Comment by beefchimi** [comment] 2021-11-20 19:21
I was getting the exact same error. I made a few changes to my `lib` config and am able to get the `storybook` server to at least start... but I then hit another `preview-web` error:

<details>
<summary><strong>Output:</strong></summary>

```
[vite] Internal server error: Failed to resolve import "@storybook/preview-web" from "../../../../../virtual:/@storybook/builder-vite/vite-app.js".

Does the file exist?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
  1  |  import fetch from 'unfetch';
  2  |  import global from 'global';
  3  |  import { composeConfigs, PreviewWeb } from '@storybook/preview-web';
     |                                              ^
  4  |  import { ClientApi } from '@storybook/client-api';
  5  |  import { addons } from '@storybook/addons';
      at formatError (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
      at TransformContext.error (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
      at normalizeUrl (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
      at async TransformContext.transform (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
      at async Object.transform (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (/home/username/path/to/project/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29)
```

</details>

I dug into the `node_modules/@storybook` folder, and indeed, `preview-web` was not there. So, I manually copied the `preview-web` folder from another project, ran `npm run storybook` again, and hit this:

<details>
<summary><strong>Output:</strong></summary>

```
info => Using cached manager
 > node_modules/@storybook/preview-web/dist/esm/composeConfigs.js:27:34: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
    27 │ import { combineParameters } from '@storybook/store';
       ╵                                   ~~~~~~~~~~~~~~~~~~

 > node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:32:35: error: Could not resolve "synchronous-promise" (mark it as external to exclude it from the bundle)
    32 │ import { SynchronousPromise } from 'synchronous-promise';
       ╵                                    ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:36:27: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
    36 │ import { StoryStore } from '@storybook/store';
       ╵                            ~~~~~~~~~~~~~~~~~~

ERR! Error: Build failed with 3 errors:
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:32:35: error: Could not resolve "synchronous-promise" (mark it as external to exclude it from the bundle)
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:36:27: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
ERR! node_modules/@storybook/preview-web/dist/esm/composeConfigs.js:27:34: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
ERR!     at failureErrorWithLog (/home/username/path/to/project/node_modules/esbuild/lib/main.js:1493:15)
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:1151:28
ERR!     at runOnEndCallbacks (/home/username/path/to/project/node_modules/esbuild/lib/main.js:941:63)
ERR!     at buildResponseToResult (/home/username/path/to/project/node_modules/esbuild/lib/main.js:1149:7)
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:1258:14
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:629:9
ERR!     at handleIncomingPacket (/home/username/path/to/project/node_modules/esbuild/lib/main.js:726:9)
ERR!     at Socket.readFromStdout (/home/username/path/to/project/node_modules/esbuild/lib/main.js:596:7)
ERR!     at Socket.emit (node:events:390:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR!     at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
ERR!  Error: Build failed with 3 errors:
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:32:35: error: Could not resolve "synchronous-promise" (mark it as external to exclude it from the bundle)
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:36:27: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
ERR! node_modules/@storybook/preview-web/dist/esm/composeConfigs.js:27:34: error: Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)
ERR!     at failureErrorWithLog (/home/username/path/to/project/node_modules/esbuild/lib/main.js:1493:15)
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:1151:28
ERR!     at runOnEndCallbacks (/home/username/path/to/project/node_modules/esbuild/lib/main.js:941:63)
ERR!     at buildResponseToResult (/home/username/path/to/project/node_modules/esbuild/lib/main.js:1149:7)
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:1258:14
ERR!     at /home/username/path/to/project/node_modules/esbuild/lib/main.js:629:9
ERR!     at handleIncomingPacket (/home/username/path/to/project/node_modules/esbuild/lib/main.js:726:9)
ERR!     at Socket.readFromStdout (/home/username/path/to/project/node_modules/esbuild/lib/main.js:596:7)
ERR!     at Socket.emit (node:events:390:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR!     at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) {
ERR!   errors: [
ERR!     {
ERR!       detail: undefined,
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "synchronous-promise" (mark it as external to exclude it from the bundle)'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "@storybook/store" (mark it as external to exclude it from the bundle)'
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }
```

</details>

I'm going to continue troubleshooting, but I don't  have much more time today.

**Comment by IanVS** [comment] 2021-11-20 21:35
This looks like a duplicate of https://github.com/eirslett/storybook-builder-vite/issues/161.  Please use 0.1.8 until we can find a way to solve it.

**Closed by IanVS** 2021-11-20 21:35 UTC
