### ISSUE TITLE
Basic init setup fails to run Storybook [React, Typescript]

### ISSUE THREAD

**Issue by aminix** [eirslett/storybook-builder-vite#139] opened 2021-11-03 17:13 UTC
Hi!

**Problem:**
Storybook fails to start when doing the basic example with React and Typescript.

**System 1 (I tried in 2 laptops)**
1. Node v16.13.0
2. npm v8.1.0 
2. macOS Monterey v12.0.1

**System :**
1. Node  v14.15.4
2. npm 7.6.0 
2. macOS Big Sur v11.6

**Steps**
1. `npm init vite@latest`
2. Choose `react` and `react-ts`
3. `cd` into the project and run `npm install && npm run dev`: it all works fine
4. Now run `npx sb@next init --builder storybook-builder-vite` (this works fine)
5. Now run `npm run storybook`

**Error**
Storybook crashes, logs:
```
> npm run storybook

> vite-app@0.0.0 storybook
> start-storybook -p 6006

info @storybook/react v6.4.0-beta.26
info
info => Loading presets
info => Using prebuilt manager
Pre-bundling dependencies:
  react
  react-dom
  @base2/pretty-print-object
  @emotion/core
  @emotion/is-prop-valid
  (...and 70 more)
(this will be run only when your dependencies or config have changed)
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 6.4.0-beta.26 for React started        │
│   648 ms for preview                               │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.88.20:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@storybook_client-api.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@storybook_client-logger.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@storybook_react.js" points to missing source files
[BABEL] Note: The code generator has deoptimised the styling of /Users/amina/Documents/Projects/vite-app/node_modules/.vite/chunk-MHXLKORO.js?v=e8b96788 as it exceeds the max of 500KB.
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/chunk-AKDXD5X2.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/regenerator-runtime_runtime_js.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/react.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@mdx-js_react.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/chunk-PHBKWG7E.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/chunk-35YZ7F37.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/ts-dedent.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@storybook_addon-docs.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/chunk-JQLGGSPV.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/util-deprecate.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/prop-types.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/global.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/react-element-to-jsx-string/dist/esm/index.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/@storybook_csf.js" points to missing source files
Sourcemap for "/Users/amina/Documents/Projects/vite-app/node_modules/.vite/qs.js" points to missing source files
node:events:368
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 56853
    at Receiver$1.controlMessage (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50517:18)
    at Receiver$1.getData (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50385:42)
    at Receiver$1.startLoop (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50110:22)
    at Receiver$1._write (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50045:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver$1.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:52459:37)
    at Socket.emit (node:events:402:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
Emitted 'error' event on WebSocket$2 instance at:
    at Receiver$1.receiverOnError (/Users/amina/Documents/Projects/vite-app/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:52346:13)
    at Receiver$1.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_INVALID_CLOSE_CODE',
  [Symbol(status-code)]: 1002
```

This is a great project btw! A time saver for sure. I can't figure out what's going on, I appreciate any suggestions.

**Comment by IanVS** [comment] 2021-11-03 17:54
Can you try an `rm -rf node_modules && npm install` and try again?  I wonder if something got into a funky state.

**Comment by aminix** [comment] 2021-11-03 19:04
@IanVS thanks for the reply. I just tried it but no luck.

**Comment by fsblemos** [comment] 2021-11-03 20:45
I was having a similar issue, then I did this:

```js
// .storybook/main.js
async viteFinal(config) {
    config.server.port = 6001; 
    config.server.https = false;
    config.server.host = true;
    config.server.hmr =  {
      port: 443,
      protocol: 'ws'
    }

    return config
  }
}
```

and it solved for me (reference https://github.com/vitejs/vite/pull/1926#issuecomment-774728965)

**Comment by IanVS** [comment] 2021-11-04 01:07
Hmmmm, that's still a little strange, and not something that I needed to configure thus far...

Which version of vite are you using?  And after reinstalling node modules, do you still see the missing sourcemap messages?

**Comment by shilman** [comment] 2021-11-04 06:02
The latest beta has moved from SSE to websockets for conveying Story index changes from node to the browser, so that's probably what's different cc @tmeasday

**Comment by aminix** [comment] 2021-11-04 10:12
@fsblemos that worked! Thank you 😄 

For the record, these are the deps in my package.json
```
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@storybook/addon-actions": "^6.4.0-beta.26",
    "@storybook/addon-essentials": "^6.4.0-beta.26",
    "@storybook/addon-links": "^6.4.0-beta.26",
    "@storybook/react": "^6.4.0-beta.26",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react": "^1.0.0",
    "babel-loader": "^8.2.3",
    "storybook-builder-vite": "^0.1.5",
    "typescript": "^4.3.2",
    "vite": "^2.6.4"
  }
```
`vite` version installed `2.6.13`
`storybook-builder-vite` version installed `0.1.5`

I'll close the thread because my specific problem is solved. Thank you all.

**Comment by tmeasday** [comment] 2021-11-04 10:45
Ok it sounds like there is a conflict between SB's websocket and Vite's @IanVS. Would it just make sense to change the default port that Vite uses like @fsblemos has done here in the builder?

**Comment by IanVS** [comment] 2021-11-04 11:26
Yes, it sounds like that is what we should do.

**Comment by spaceninja** [comment] 2021-11-06 17:01
I posted a similar bug over on Storybook — https://github.com/storybookjs/storybook/issues/16616 — and got sent over here. Pleased to say the fix in this thread solved my problem too.

**Comment by larswww** [comment] 2021-11-08 20:57
Hello! I was getting;

`RangeError: Invalid WebSocket frame: invalid status code 65000` thrown by `events.js:377`, so a slightly different code.

Fix also worked for me, without configType === 'DEVELOPMENT'

**Comment by eirslett** [comment] 2021-11-08 21:36
Would it be possible to solve this issue without changing the Websocket port?

```javascript
// pseudocode just to illustrate
var viteWS = new WebSocket("ws://localhost:6006/vite");
var storybookWS = new WebSocket("ws://localhost:6006/storybook");

viteWS.onmessage = function (event) {
  alert("Some Vite HMR stuff going on");
};

storybookWS.onmessage = function (event) {
  alert("Some Storybook story index update"); 
};
```

It should be possible to differentiate between the websockets based on their URL path?

**Comment by tmeasday** [comment] 2021-11-09 03:38
We could make that change in Storybook if it helps, but it sounds like the Vite builder needs to make a change anyway 🤷

**Comment by IanVS** [comment] 2021-11-09 04:26
I've got a PR ready to go, but then I realized that we'll need to change the config to ws only for certain versions of storybook, right?  Is there any kind of flag that we can use to determine this, so we don't need to parse the version string from `options.packageJson.version` and apply semver rules to it to determine whether or not we should use websockets?

I guess the other alternative would be to make a new minor (breaking) release of storybook-builder-vite that requires storybook 6.4.0-beta.? (when was the change to ws exactly?).

**Comment by eirslett** [comment] 2021-11-09 10:59
I mentioned it in #144 - is it possible to push back the SSE->Websocket change in Storybook until 6.5 (or put it behind a feature flag) which could buy us some time fo figure out how to solve this?

**Comment by tmeasday** [comment] 2021-11-09 20:18
> I've got a PR ready to go, but then I realized that we'll need to change the config to ws only for certain versions of storybook, right? Is there any kind of flag that we can use to determine this, so we don't need to parse the version string from options.packageJson.version and apply semver rules to it to determine whether or not we should use websockets?

Hmm, I don't think I'm quite following. Here's how I understand the situation, please forgive me if I have it wrong:

1. For HMR, Vite uses a websocket, by default on the same port as the (HTTP) webserver
2. In 6.4, in v7 mode, Storybook **also** uses a websocket, on the same port as the (HTTP) webserver
3. Unsurprisingly that causes a problem as the sockets are conflicting with each other.

The solution as suggested on this thread is just to change Vite's configuration to use a different port for (1). 

I'm not really sure why you wouldn't just do that all the time @IanVS? Is there any reason why you'd only want to do it for situations where there'd otherwise be a conflict?

> I mentioned it in #144 - is it possible to push back the SSE->Websocket change in Storybook until 6.5 (or put it behind a feature flag) which could buy us some time fo figure out how to solve this?

Hmm, not really, the SSE solution really didn't work and caused SB to hang if you had more than 1 tab open to the same Storybook. This is all behind the v7 store feature flag already, but that probably doesn't help much because that's the ideal mode for Vite.

Maybe ping me on Discord? I can make any changes we need on the SB end pretty easily (ie. only serving the SB websocket on a path, maybe?)

**Comment by tmeasday** [comment] 2021-11-09 20:21
Oh, now I just read the comment from https://github.com/eirslett/storybook-builder-vite/pull/144#issuecomment-964033992

> One of the limitations of going this route is that it's hardcoded to port 443, would could be used for something else, there is no port conflict resolution like in Storybook (suggests using port 6007 whenever port 6006 is busy) etc., also you won't be able to run two Storybooks at the same time locally. (Maybe not such a big deal?)

Can someone tell me how to reproduce the problem? I can take a look at what we can do without changing the Vite configuration.

**Comment by nVitius** [comment] 2021-11-10 20:55
@tmeasday I was able to reproduce this by just creating a new vite project and adding storybook:
```
npm init vite@latest
npx sb@next init --builder storybook-builder-vite
```

**Comment by tmeasday** [comment] 2021-11-11 08:05
Fix here: https://github.com/storybookjs/storybook/pull/16665

**Comment by eirslett** [comment] 2021-11-11 12:09
> Fix here: storybookjs/storybook#16665

I haven't tried it, but it looks to me like this should be an acceptable solution! Not sure if we also have to make any changes on the Storybook-builder-vite side, we'll have to investigate that a bit.

**Comment by tmeasday** [comment] 2021-11-11 22:24
From my experiments you should be OK without changes but LMK.

**Comment by alb3rtuk** [comment] 2021-11-12 15:47
OMG... thank you for fixing this. I just ran 6.4.0-beta.33 and can confirm the hot reload is fixed :)

**Comment by IanVS** [comment] 2021-11-12 16:29
Storybook 6.4.0-rc.0 has just been released, and I've verified that it works with the vite-builder out of the box with no config changes needed.  So for those in this thread, I suggest you revert the changes you made to your `viteFinal`, and upgrade to the release candidate.  I'll close this out, but feel free to open a new issue if you continue to have problems with the latest version of storybook.

**Closed by IanVS** 2021-11-12 16:29 UTC
