### ISSUE TITLE
Vite cannot resolve `optimizeDeps` when using pnpm

### ISSUE THREAD

**Issue by gavinxgu** [eirslett/storybook-builder-vite#61] opened 2021-07-04 12:28 UTC
Maybe we should make vite as dependency instead of peer dependency like [storybook-builder-webpack5](https://github.com/storybookjs/storybook/blob/master/lib/builder-webpack5/package.json#L95) and [storybook-builder-webpack4](https://github.com/storybookjs/storybook/blob/master/lib/builder-webpack4/package.json#L104)

**Comment by eirslett** [comment] 2021-07-04 17:20
This issue seems like a duplicate of #55.

**Closed by eirslett** 2021-07-04 17:20 UTC
