### ISSUE TITLE
Storybook won't start when used in a pnpm workspace

### ISSUE THREAD

**Issue by robcaldecott** [eirslett/storybook-builder-vite#237] opened 2022-02-11 11:48 UTC
Note that I reported this on the main Storybook repo but was told to report it here:

https://github.com/storybookjs/storybook/issues/17342#issuecomment-1033654619

**Describe the bug**
I am experimenting with `pnpm` as its monorepo support is excellent. However, when using Storybook with `storybook-builder-vite` in a workspace it will not start and instead displays the following error:

```
info => Loading presets
ERR! Error: [vite-plugin-mdx] "@mdx-js/react" must be installed
ERR!     at resolveImport (/Users/caldecor/Projects/pnpm-storybook/node_modules/.pnpm/artifactory.keyloop.com+vite-plugin-mdx@3.5.10_@mdx-js+mdx@1.6.22+vite@2.7.13/node_modules/vite-plugin-mdx/dist/imports.js:29:23)
<snip>
```

On the face of it this looks like a dependency resolution issue as the same repo will work OK using `npm8` or `yarn1` workspaces.

**To Reproduce**
You will need `pnpm` installed (`npm install -g pnpm`).

Clone the following repo: https://github.com/robcaldecott/pnpm-storybook and then:

```
pnpm install
cd packages/components
pnpm storybook
```

**System**

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 95.0.2
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.4.14 => 6.4.14 
    @storybook/addon-essentials: ^6.4.14 => 6.4.14 
    @storybook/addon-links: ^6.4.14 => 6.4.14 
    @storybook/react: ^6.4.14 => 6.4.14 
```

**Additional context**
There is a proposed workaround by creating a `.npmrc` file in the root of the repo that looks like this:

```
node-linker=hoisted
```

However this causes `pnpm` some issues and seems like a last resort.

**Comment by robcaldecott** [comment] 2022-02-11 11:49
FWIW when using hoisting it exposes a bizarre `pnpm` issue!

https://github.com/pnpm/pnpm/issues/4284

**Comment by 0xsha256** [comment] 2022-02-12 15:56
> Could be. All the errors I'm saying are from `vite-plugin-mdx`

I'm having the exact same problem. I installed `@mdx-js/preact`, but I'm just getting `Failed to load resource: the server responded with a status of 408 (Request Timeout)`

**Comment by IanVS** [comment] 2022-02-17 04:47
There are some workarounds in that other issue, have you tried them out?

**Comment by ufon** [comment] 2022-02-22 13:53
```
  async viteFinal(config, { configType }) {
    const { dirname } = require('path');
    
    // https://github.com/eirslett/storybook-builder-vite/issues/55
    config.root = dirname(require.resolve('storybook-builder-vite'));
    // config.server.fsServe = {};
    return config;
  },
```

Working for me.

**Comment by zeyuri** [comment] 2022-03-13 02:47
@ufon is this is still working for you? Which version of the plugin are you using?

Can you please share a working example of this? I'm struggling very hard to make this work.

**Comment by CalebKester** [comment] 2022-03-15 13:59
@zeyuri I was just able to set this up in my pnpm project by adding `shamefully-hoist=true` to the .npmrc file. I'm still testing and configuring it so there might be more issues but the initial example worked just fine. Next week i'll be linking my components from shared libraries and will report back on it.

**Comment by IanVS** [comment] 2022-03-17 01:46
Closing as a duplicate of https://github.com/eirslett/storybook-builder-vite/issues/55.  Definitely something on our radar, and we'd love if anyone was able to find a way to solve this without requiring shame.

**Closed by IanVS** 2022-03-17 01:46 UTC

**Comment by grinsteindavid** [comment] 2022-05-03 21:33
I just move from pnpm in rushjs to npm and it works perfect

**Comment by grinsteindavid** [comment] 2022-05-03 21:34
NPM works just fine

**Comment by wilbsy** [comment] 2022-11-29 14:07
.npmrc file in root directory with the following lines solved for me:
```
auto-install-peers = true
node-linker=hoisted
```

**Comment by palerdot** [comment] 2023-02-23 06:17
> ```
>   async viteFinal(config, { configType }) {
>     const { dirname } = require('path');
>     
>     // https://github.com/eirslett/storybook-builder-vite/issues/55
>     config.root = dirname(require.resolve('storybook-builder-vite'));
>     // config.server.fsServe = {};
>     return config;
>   },
> ```
> 
> Working for me.

@ufon solution works for me. I just had to tweak the require to `@storybook/builder-vite`
