### ISSUE TITLE
Unable to load stories from a fresh installation

### ISSUE THREAD

**Issue by tur-nr** [eirslett/storybook-builder-vite#97] opened 2021-09-21 10:16 UTC
### Bug description

When I start storybook I get the skeleton with a spinner. When inspecting the dev-tools I can see that `/stories.json` was not found. I don't know the internals of storybook but I imagine that file is like the manifest?

![image](https://user-images.githubusercontent.com/817134/134152898-fd57b5d8-5b60-4d45-a4b7-86a8108dfb0c.png)

### Steps to reproduce

Follow these commands (I did not touch any code).

```
$ npm init vite demo-app
$ cd demo-app
$ npm i
$ npx sb@next init --builder storybook-builder-vite
$ npm run storybook
```

### Debug information

- node: `14.17.3`
- npm: `6.14.13`

```json
{
  "name": "demo-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@storybook/addon-actions": "^6.4.0-alpha.40",
    "@storybook/addon-essentials": "^6.4.0-alpha.40",
    "@storybook/addon-links": "^6.4.0-alpha.40",
    "@storybook/react": "^6.4.0-alpha.40",
    "@vitejs/plugin-react-refresh": "^1.3.1",
    "babel-loader": "^8.2.2",
    "storybook-builder-vite": "0.0.12",
    "vite": "^2.5.4"
  }
}
```

```ini
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by joshwooding** [comment] 2021-11-20 00:34
@silverspace @tur-nr This should be fixed with 0.1.8+ can you confirm?

**Comment by tur-nr** [comment] 2021-11-21 00:50
@joshwooding thanks for the update on this issue. Seems a bit of a odd one because using `yarn` works perfectly thanks. However `npm` does not, seems like the installed dependencies differ between the two package managers causing `npm` to fail.

```
$ npm run storybook

> demo-app@0.0.0 storybook /demo-app
> start-storybook -p 6006

info @storybook/react v6.4.0-rc.5
info 
info => Loading presets
info => Using prebuilt manager
Pre-bundling dependencies:
  react
  react-dom
  @base2/pretty-print-object
  @emotion/core
  @emotion/is-prop-valid
  (...and 75 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:33:17: error: No matching export in "node_modules/storybook-builder-vite/node_modules/@storybook/core-events/dist/esm/index.js" for import "IGNORED_EXCEPTION"
    33 │ import Events, { IGNORED_EXCEPTION } from '@storybook/core-events';
       ╵                  ~~~~~~~~~~~~~~~~~

ERR! Error: Build failed with 1 error:
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:33:17: error: No matching export in "node_modules/storybook-builder-vite/node_modules/@storybook/core-events/dist/esm/index.js" for import "IGNORED_EXCEPTION"
ERR!     at failureErrorWithLog (/demo-app/node_modules/esbuild/lib/main.js:1493:15)
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:1151:28
ERR!     at runOnEndCallbacks (/demo-app/node_modules/esbuild/lib/main.js:941:63)
ERR!     at buildResponseToResult (/demo-app/node_modules/esbuild/lib/main.js:1149:7)
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:1258:14
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:629:9
ERR!     at handleIncomingPacket (/demo-app/node_modules/esbuild/lib/main.js:726:9)
ERR!     at Socket.readFromStdout (/demo-app/node_modules/esbuild/lib/main.js:596:7)
ERR!     at Socket.emit (events.js:375:28)
ERR!     at addChunk (internal/streams/readable.js:290:12)
ERR!     at readableAddChunk (internal/streams/readable.js:265:9)
ERR!     at Socket.Readable.push (internal/streams/readable.js:204:10)
ERR!     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
ERR!  Error: Build failed with 1 error:
ERR! node_modules/@storybook/preview-web/dist/esm/PreviewWeb.js:33:17: error: No matching export in "node_modules/storybook-builder-vite/node_modules/@storybook/core-events/dist/esm/index.js" for import "IGNORED_EXCEPTION"
ERR!     at failureErrorWithLog (/demo-app/node_modules/esbuild/lib/main.js:1493:15)
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:1151:28
ERR!     at runOnEndCallbacks (/demo-app/node_modules/esbuild/lib/main.js:941:63)
ERR!     at buildResponseToResult (/demo-app/node_modules/esbuild/lib/main.js:1149:7)
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:1258:14
ERR!     at /demo-app/node_modules/esbuild/lib/main.js:629:9
ERR!     at handleIncomingPacket (/demo-app/node_modules/esbuild/lib/main.js:726:9)
ERR!     at Socket.readFromStdout (/demo-app/node_modules/esbuild/lib/main.js:596:7)
ERR!     at Socket.emit (events.js:375:28)
ERR!     at addChunk (internal/streams/readable.js:290:12)
ERR!     at readableAddChunk (internal/streams/readable.js:265:9)
ERR!     at Socket.Readable.push (internal/streams/readable.js:204:10)
ERR!     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
ERR!   errors: [
ERR!     {
ERR!       detail: undefined,
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'No matching export in "node_modules/storybook-builder-vite/node_modules/@storybook/core-events/dist/esm/index.js" for import "IGNORED_EXCEPTION"'
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-app@0.0.0 storybook: `start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-app@0.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-11-21T00_42_00_625Z-debug.log
```

```json
{
  "name": "demo-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@storybook/addon-actions": "^6.4.0-rc.5",
    "@storybook/addon-essentials": "^6.4.0-rc.5",
    "@storybook/addon-links": "^6.4.0-rc.5",
    "@storybook/react": "^6.4.0-rc.5",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react": "^1.0.0",
    "babel-loader": "^8.2.3",
    "storybook-builder-vite": "^0.1.9",
    "typescript": "^4.3.2",
    "vite": "^2.6.4"
  }
}
```

**Comment by joshwooding** [comment] 2022-01-08 00:31
@tur-nr that problem should be solved now. I'm closing this for now since I can't reproduce the issue locally anymore. Let me know if you encounter any more issues :)

**Closed by joshwooding** 2022-01-08 00:31 UTC

**Comment by tur-nr** [comment] 2022-01-11 06:33
Works perfectly with `npm` now, thanks :clap:
