### ISSUE TITLE
Vue3 could not resolve component when using build

### ISSUE THREAD

**Issue by m-barrera** [eirslett/storybook-builder-vite#80] opened 2021-07-30 16:28 UTC
Hello,

I am not quite sure if it is a bug or not. So we are building a component-library and we wanted to
switch to vite. So I added vite dependencies and adjusted the preview.js. The dev env for storybook worked
out of the box. But when trying to build it starts throwing errors. 
```
Vite v2.4.4 building for production...
✓ 52 modules transformed.
Could not resolve './dropdown' from src/components/Input/Dropdown/dropdown.stories.js
ERR! Error: Could not resolve './dropdown' from src/components/Input/Dropdown/dropdown.stories.js
```

This is only an excerpt this is repeated across multiple components. But if I only use my Icon components it does complete the build.

Version:
    "vue": "^3.1.5",
    "@storybook/addon-actions": "6.3.6",
    "@storybook/addon-essentials": "6.3.6",
    "@storybook/addon-jest": "^6.3.6",
    "@storybook/addon-links": "6.3.6",
    "@storybook/addon-viewport": "6.3.6",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/vue3": "^6.3.6",
    "storybook-builder-vite": "^0.0.12",

**Comment by eirslett** [comment] 2021-07-31 17:11
Are you able to create a minimum reproduction repo? Start with this:

```
npm init @vitejs/app vite-react-app --template react && cd vite-react-app
npm install # or yarn
npx sb@next init --builder storybook-builder-vite && npm run storybook
```
and make tweaks to it until you can reproduce the bug.

**Comment by blowsie** [comment] 2021-08-12 08:26
This part of your issue is a little confusing to me.
> But if I only use my Icon components it does complete the build.

More detail would really help anyone help

**Comment by joshwooding** [comment] 2022-01-08 00:21
Closing this since there's not been a response for a while. Happy to re-open this if the issue pops up again.

**Closed by joshwooding** 2022-01-08 00:21 UTC
Labels: needs reproduction
