### ISSUE TITLE
error: No matching export in "node_modules/storybook-builder-vite/node_modules/@storybook/core-events/dist/esm/index.js" for import "IGNORED_EXCEPTION"

### ISSUE THREAD

**Issue by olemarius** [eirslett/storybook-builder-vite#162] opened 2021-11-20 09:19 UTC
I'm getting this error in my own project without understanding why, so I tried copying example-vue to an own folder with some adjustments to make it work

- changed dependency from workspace to "storybook-builder-vite": "^0.1.9",
- remove 'main' : 'index.js' 
- add yarn / github files/folders from parent repo (storybook-builder-vite)

Here's the repo: https://github.com/olemarius/storybook-builder-vite-example-vue-in-isolation

![image](https://user-images.githubusercontent.com/184536/142720486-0afb90f3-8d6a-4bae-b782-b58701e1b10a.png)
 

PS! Opening storybook-builder-vite and running example-vue in 0.1.8 works perfect.

Easiest way to reproduce in storybook-builder-vite  repo:

1. cd packages/example-vue
2. npm i
3. npm run storybook

**Comment by IanVS** [comment] 2021-11-20 15:21
It looks like this is a duplicate of https://github.com/eirslett/storybook-builder-vite/issues/161.

**Closed** 2021-11-20 15:21 UTC
