### ISSUE TITLE
Install @vitejs/plugin-vue to handle .vue files.

### ISSUE THREAD

**Issue by thozh** [eirslett/storybook-builder-vite#7] opened 2021-04-20 10:21 UTC
Hello @eirslett 

I had the same issue as https://github.com/eirslett/storybook-builder-vite/issues/4 and thanks to your recommendation it worked (changing the `@storybook/vue3` version to `6.3.0-alpha.10`) but I'm facing a new issue with Vue3 components.

Here is the complete error log : 
```
 [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
  Plugin: vite:import-analysis
  File: /Users/thz/Documents/pro/Senz/senz-app/design/src/stories/Header.vue
  17 |                fill="#91BAF8"
  18 |              />
  19 |            </g>
     |                ^
  20 |          </svg>
  21 |          <h1>Acme</h1>
      at formatError (/Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43518:46)
      at TransformContext.error (/Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43514:19)
      at TransformContext.transform (/Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:45028:22)
      at async Object.transform (/Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:43716:30)
      at async transformRequest (/Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:59433:29)
      at async /Users/thz/Documents/pro/Senz/senz-app/design/node_modules/vite/dist/node/chunks/dep-66eb515d.js:59555:32
```

package.json
```
{
  "name": "package",
  "files": [
    "dist"
  ],
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "serve": "vite preview",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.13.15",
    "@storybook/addon-actions": "^6.2.8",
    "@storybook/addon-essentials": "^6.2.8",
    "@storybook/addon-links": "^6.2.8",
    "@storybook/builder-webpack5": "^6.3.0-alpha.12",
    "@storybook/vue3": "6.3.0-alpha.10",
    "@types/node": "^14.14.41",
    "@vitejs/plugin-vue": "^1.2.1",
    "@vue/compiler-sfc": "^3.0.5",
    "babel-loader": "^8.2.2",
    "sass": "^1.32.8",
    "sass-loader": "^11.0.1",
    "storybook-builder-vite": "^0.0.3",
    "typescript": "^4.1.3",
    "vite": "^2.1.5",
    "vue-loader": "^16.2.0",
    "vue-tsc": "^0.0.24"
  }
}

```

Do you have any ideas why @vitejs/plugin-vue is not detected please ^^' ?

**Comment by eirslett** [comment] 2021-04-20 10:39
Is this during `start-storybook` or `build-storybook`? Looks like in build.js I forgot to add the vue plugin. For start/dev, it should work, I'm not sure why it's not triggered...

**Comment by thozh** [comment] 2021-04-20 10:43
Thanks for your quick response 😀

It's on the `start-storybook` command

**Comment by eirslett** [comment] 2021-04-20 10:48
```
if (framework === 'vue') {
        const vuePlugin = await import('@vitejs/plugin-vue').then((plugin) =>
            plugin.default()
        );
        plugins.push(vuePlugin);
    }
```
The code is doing this... why is it even using import() in the first place, this is CommonJS so it should use require(). 🤦

**Comment by youngpirate32** [comment] 2021-04-21 00:54
My framework value is vue3, instead of vue

**Comment by eirslett** [comment] 2021-04-21 15:17
Ah, that explains it! @SasanFarrokh do you know if we need to configure Vite differently for Vue 3 than for earlier versions?

**Comment by eirslett** [comment] 2021-04-24 12:00
I updated the plugin now, I think it should work with Vue. @thozh could you please try again, see if it works for you now?

**Comment by eirslett** [comment] 2021-04-27 18:58
Closing this - feel free to reopen if it's still an issue.

**Closed by eirslett** 2021-04-27 18:58 UTC

**Comment by Gelocg** [comment] 2022-09-11 21:16
Yo ! I have the same issue and i don't understand why ?

**Comment by IanVS** [comment] 2022-09-11 21:23
@Gelocg would you mind opening a new issue with the details of what you're seeing, and ideally a reproduction or link to your repo that we can use to investigate?

**Comment by n3ur0n** [comment] 2022-10-27 14:15
> Yo ! I have the same issue and i don't understand why ?

I have added vite.config.js and it works now for me.
```
const vue = require('@vitejs/plugin-vue2');
import { defineConfig } from "vite";

export default defineConfig({
    plugins: [vue()]
});
```

**Comment by jokinend** [comment] 2025-02-07 21:10
Here's a contemporary solution to this problem for Vue 3 with TypeScript, inspired by [this earlier solution for Vue 2 with JavaScript](https://github.com/storybookjs/builder-vite/issues/7#issuecomment-1293591721).

Update file `vite.renderer.config.ts` to include:

```typescript
import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [vue()]
});
```
